version: 2.1

orbs:
  node: circleci/node@5.1.0

jobs:
  build-and-test:
    docker:
      - image: cimg/node:18.19
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run tests
          command: npm run test:ci
      - run:
          name: Run lint
          command: npm run lint
      - run:
          name: Build package
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - .

  publish:
    docker:
      - image: cimg/node:18.19
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - run:
          name: Publish package
          command: npm publish

workflows:
  version: 2
  build-test-publish:
    jobs:
      - build-and-test
      - publish:
          requires:
            - build-and-test
          filters:
            branches:
              only: main
            tags:
              only: /^v.*/
